#!/bin/bash

root="${1}"; shift
command="GRAPHDIFF"
: ${TOOL_JAR:=dpdgraph-parser.jar}

if [ ! -f "${TOOL_JAR}" ]; then
        echo "ERROR: icoq jar is not available (at ${TOOL_JAR})."
        exit 1
fi

if [ ! -f "${root}/.comap" ]; then
        command="GRAPHNEW"
fi

java -classpath \
        "${TOOL_JAR}" \
        edu.utexas.ece.icoq.Icoq \
        -root ${root} \
        -command ${command} \
        -configCommand "-" \
        "$@"
